#!/bin/sh

bspc rule -r "*"

###---Autostart---###
bluetoothctl power on &
remaps &
setbg &
picom &
dunst &
xset r rate 300 50 &
unclutter &
sxhkd &
mpd &
launch_polybar

###---MONITORS---###
bspc monitor $mainmonitor -d 1 2 3 4 5
bspc desktop -f 1

###---Global Settings---###

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config border_width                  4
bspc config window_gap                    10
bspc config top_padding                   25
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors 	  true
bspc config remove_unplugged_monitors 	  true
bspc config merge_overlapping_monitors 	  true

bspc config normal_border_color		"#504945"
bspc config active_border_color		"#504945"
bspc config focused_border_color 	"#005577"
bspc config presel_feedback_color 	"#504945"
bspc config urgent_border_color 	"#ff0000"

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above
